services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: portal:local
    container_name: portal
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html/data
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    restart: unless-stopped
